import { writable } from "svelte/store";

export interface DocumentState {
  content: string;
  path: string | null;
  title: string;
  isDirty: boolean;
  isLoading: boolean;
}

const defaultContent = [
  "# Welcome to MarkZ",
  "",
  "> **The engineer's Markdown editor.** Built for speed, designed for clarity, and optimized for the tools you already use.",
  "",
  "MarkZ is a dual-pane Markdown editor that helps you write, preview, and export engineering documents without friction. Whether you're drafting RFCs, documenting APIs, or preparing content for JIRA and Confluence, MarkZ keeps you in flow.",
  "",
  "---",
  "",
  "## What Makes MarkZ Different",
  "",
  "| Feature | Description |",
  "|---------|-------------|",
  "| **Live Preview** | See your document render instantly as you type |",
  "| **Export Pipeline** | One-click export to JIRA, Confluence, Slack, GitHub, and DOCX |",
  "| **Image Handling** | Paste from clipboard or drag-and-drop — images are organized automatically |",
  "| **Syntax Highlighting** | 30+ languages with tree-sitter accuracy |",
  "| **Math & Diagrams** | KaTeX for equations, Mermaid for flowcharts |",
  "| **Templates** | Built-in RFC, ADR, Bug Report, and more |",
  "",
  "---",
  "",
  "## Quick Start",
  "",
  "### 1. Write Markdown",
  "MarkZ supports standard CommonMark plus extensions:",
  "",
  "**Formatting:** *italic*, **bold**, `inline code`, ~~strikethrough~~",
  "",
  "**Lists:**",
  "- Unordered items",
  "- [x] Completed tasks",
  "- [ ] Pending tasks",
  "",
  "**Code blocks** with syntax highlighting:",
  "```rust",
  'fn main() {',
  '    println!("Hello, MarkZ!");',
  '}',
  "```",
  "",
  "### 2. Preview Your Work",
  "The right pane renders your document in real time. Toggle between **HTML**, **JIRA**, **Confluence**, **Slack**, and **GitHub** preview modes to see exactly how your content will look in each platform.",
  "",
  "### 3. Export Cleanly",
  'MarkZ exports **only what you write** — no watermarks, no "created with" banners, no unwanted metadata. Your content stays yours.',
  "",
  "---",
  "",
  "## Keyboard Shortcuts",
  "",
  "| Shortcut | Action |",
  "|----------|--------|",
  "| `Ctrl + S` | Save document |",
  "| `Ctrl + O` | Open file |",
  "| `Ctrl + T` | New tab |",
  "| `Ctrl + W` | Close tab |",
  "| `Ctrl + B` | Toggle outline sidebar |",
  "| `Ctrl + =` | Zoom in |",
  "| `Ctrl + -` | Zoom out |",
  "| `Ctrl + 0` | Reset zoom |",
  "",
  "---",
  "",
  "## Formatting Reference",
  "",
  "This section exercises every formatting feature MarkZ supports.",
  "",
  "### Headings",
  "# Heading 1",
  "## Heading 2",
  "### Heading 3",
  "#### Heading 4",
  "##### Heading 5",
  "###### Heading 6",
  "",
  "### Inline Formatting",
  "Normal text, **bold text**, *italic text*, ~~strikethrough~~, and `inline code`.",
  "",
  "Combined: ***bold italic***, **`bold code`**, *`italic code`**.",
  "",
  "[External link to example.com](https://example.com)",
  "",
  "### Code Blocks",
  "",
  "#### Rust",
  "```rust",
  'fn main() {',
  '    let message = "Hello, MarkZ!";',
  '    println!("{}", message);',
  '}',
  "```",
  "",
  "#### Python",
  "```python",
  "def fibonacci(n):",
  "    a, b = 0, 1",
  "    for _ in range(n):",
  "        yield a",
  "        a, b = b, a + b",
  "",
  "print(list(fibonacci(10)))",
  "```",
  "",
  "#### JSON",
  "```json",
  '{',
  '  "name": "MarkZ",',
  '  "version": "0.1.0",',
  '  "features": ["preview", "export", "templates"]',
  '}',
  "```",
  "",
  "### Blockquotes",
  "> Single-level blockquote with **bold** and `code`.",
  "",
  "> Multi-paragraph blockquote.",
  ">",
  "> Second paragraph with a [link](https://example.com).",
  "",
  "> > Nested blockquote level 2",
  "> >",
  "> > > Nested blockquote level 3",
  "",
  "### Lists",
  "",
  "#### Unordered",
  "- First item",
  "- Second item",
  "  - Nested item A",
  "  - Nested item B",
  "    - Deep nested item",
  "- Third item",
  "",
  "#### Ordered",
  "1. First step",
  "2. Second step",
  "   1. Sub-step A",
  "   2. Sub-step B",
  "3. Third step",
  "",
  "#### Task List",
  "- [x] Completed task",
  "- [ ] Pending task",
  "- [ ] Another pending task",
  "  - [x] Sub-task done",
  "  - [ ] Sub-task waiting",
  "",
  "#### Mixed",
  "1. Ordered first",
  "   - Unordered nested",
  "   - Another nested",
  "2. Ordered second",
  "   1. Ordered nested",
  "   2. Another nested",
  "",
  "### Tables",
  "",
  "#### Simple Table",
  "| Feature | Status | Notes |",
  "|---------|--------|-------|",
  "| Headings | ✅ | All 6 levels |",
  "| Bold/Italic | ✅ | Combined styles |",
  "| Code Blocks | ✅ | Syntax highlighting |",
  "| Tables | ✅ | This one! |",
  "| Images | ✅ | Local & remote |",
  "",
  "#### Alignment Table",
  "| Left | Center | Right |",
  "|:-----|:------:|------:|",
  "| L1   | C1     | R1    |",
  "| L2   | C2     | R2    |",
  "| L3   | C3     | R3    |",
  "",
  "### Horizontal Rules",
  "Above rule.",
  "",
  "---",
  "",
  "Below rule with **bold** text.",
  "",
  "***",
  "",
  "Another rule.",
  "",
  "### Images",
  "",
  "#### Remote Images",
  "MarkZ renders remote images directly in the preview. These samples use free placeholder photos:",
  "",
  "![Remote landscape photo](https://picsum.photos/seed/markz1/600/300)",
  "",
  "![Remote portrait photo](https://picsum.photos/seed/markz2/300/400)",
  "",
  "![Remote square photo](https://picsum.photos/seed/markz3/400/400)",
  "",
  "> 💡 **Tip:** Toggle *Settings → Embed remote images* to download these into exports.",
  "",
  "### Special Characters & Escapes",
  "- Asterisk: \\*not italic\\*",
  "- Hash: \\# not heading",
  "- Backtick: \\`not code\\`",
  "- Ampersand: AT&T",
  "- Less/Greater: 5 < 10 > 2",
  "- Emoji: 🚀 ✅ ❌ 💡",
  "",
  "---",
  "",
  "## Math",
  "",
  "Inline math: $E = mc^2$ and $\\vec{F} = m\\vec{a}$",
  "",
  "Block math:",
  "$$",
  "\\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}",
  "$$",
  "",
  "Matrix:",
  "$$",
  "\\begin{bmatrix}",
  "a & b \\\\",
  "c & d",
  "\\end{bmatrix}^{-1}",
  "=",
  "\\frac{1}{ad-bc}",
  "\\begin{bmatrix}",
  "d & -b \\\\",
  "-c & a",
  "\\end{bmatrix}",
  "$$",
  "",
  "---",
  "",
  "## Mermaid Diagram",
  "",
  "```mermaid",
  "graph TD",
  "    A[Markdown Editor] --> B[Parser]",
  "    B --> C[AST]",
  "    C --> D[HTML Renderer]",
  "    C --> E[DOCX Converter]",
  "    C --> F[JIRA Converter]",
  "    D --> G[Preview Pane]",
  "    E --> H[File Export]",
  "    F --> I[Clipboard]",
  "```",
  "",
  "---",
  "",
  "## HTML Details (if supported)",
  "",
  "<details>",
  "<summary>Click to expand</summary>",
  "",
  "Hidden content inside a details block.",
  "",
  "</details>",
  "",
  "---",
  "",
  "*Welcome to MarkZ*",
].join("\n");

function createDocumentStore() {
  const { subscribe, set, update } = writable<DocumentState>({
    content: defaultContent,
    path: null,
    title: "Untitled",
    isDirty: false,
    isLoading: false,
  });

  return {
    subscribe,
    setContent: (content: string) =>
      update((s) => ({ ...s, content, isDirty: true })),
    loadDocument: (content: string, path: string) =>
      update((s) => ({
        ...s,
        content,
        path,
        title: path.split(/[\\/]/).pop() || "Untitled",
        isDirty: false,
        isLoading: false,
      })),
    setPath: (path: string | null) =>
      update((s) => ({
        ...s,
        path,
        title: path ? path.split(/[\\/]/).pop() || "Untitled" : "Untitled",
      })),
    markClean: () => update((s) => ({ ...s, isDirty: false })),
    markDirty: () => update((s) => ({ ...s, isDirty: true })),
    setLoading: (loading: boolean) =>
      update((s) => ({ ...s, isLoading: loading })),
    setState: (state: DocumentState) => set(state),
    newFromTemplate: (content: string, name: string) =>
      set({
        content,
        path: null,
        title: name,
        isDirty: true,
        isLoading: false,
      }),
    reset: () =>
      set({
        content: defaultContent,
        path: null,
        title: "Untitled",
        isDirty: false,
        isLoading: false,
      }),
  };
}

export const documentStore = createDocumentStore();
