[package]
name = "markz-images"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
markz-core = { path = "../markz-core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
dirs = { workspace = true }
chrono = { version = "0.4" }

[dev-dependencies]
tempfile = "3"
