[package]
name = "markz-convert"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
markz-core = { path = "../markz-core" }
serde = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
docx-rs = { workspace = true }
ureq = { workspace = true }
base64 = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "bmp", "tiff"] }
